import entry0 from "./entries/living-geometry.json";
import entry1 from "./entries/projecting-the-anthropocene.json";
import entry2 from "./entries/passage-of-water.json";
import entry3 from "./entries/mirror-mirror-on-the-wall.json";
import entry4 from "./entries/oscillating-cultures.json";
import entry5 from "./entries/ling.json";
import type { Project } from "./types";
export const menuDescription = "Selected projects.";
export const projects: Project[] = [entry0, entry1, entry2, entry3, entry4, entry5];
export type { Project } from "./types";
