import type { Artwork } from "./types";

// Text and imagery curated from the XD Lab record and documented sources.
// Image provenance and secondary-source review: ./SOURCES.md.
export const banpoXism: Artwork = {
  slug: "banpo-xism",
  title: "Banpo-Xism",
  year: "2026",
  menuDescription: "Criticising South Korean Apartment Republic through Higher-Dimensional Geometry",
  width: 960, height: 720,
  creators: ["Jeanyoon Choi"],
  venue: "<Living Geometry>",
  exhibitions: [{ name: "Living Geometry", venue: "Yeongdeungpo Art Square", dates: "1 May – 28 June 2026", url: "https://www.xdlab.net/living-geometry-archive" }],
  site: "https://banpo-xism.vercel.app/",
  image: "/artworks/banpo-xism/1.webp",
  images: [
    {
      "src": "/artworks/banpo-xism/1.webp",
      "alt": "Visitor holding a phone in front of the Banpo-Xism installation.",
      "width": 1920,
      "height": 2879,
      "caption": "Audience interaction with the Media Wall through a mobile phone."
    },
    {
      "src": "/artworks/banpo-xism/2.webp",
      "alt": "Banpo-Xism: mobile interface sequence from feed to advertisement and grid.",
      "caption": "The mobile experience moves from an SNS-like apartment feed through an advertisement to the grid interface.",
      "width": 1920,
      "height": 2775
    },
    {
      "src": "/artworks/banpo-xism/3.webp",
      "alt": "Banpo-Xism: blue folded apartment geometry on the media wall.",
      "width": 1920,
      "height": 1281,
      "caption": "The apartment field folds into a blue higher-dimensional form on the Media Wall."
    },
    {
      "src": "/artworks/banpo-xism/4.webp",
      "alt": "Wide installation view of Banpo-Xism with three vertical screens and a white geometric apartment field.",
      "width": 1920,
      "height": 1103,
      "caption": "Installation overview of 『Banpo-Xism』: a Media Wall and three vertical TVs."
    },
    {
      "src": "/artworks/banpo-xism/5.webp",
      "alt": "Banpo-Xism: annotated installation structure showing Media Wall and three TVs.",
      "caption": "Installation structure: the Media Wall and three vertical TVs show different projections of the apartment field.",
      "width": 1920,
      "height": 1581
    },
    {
      "src": "/artworks/banpo-xism/6.webp",
      "alt": "Banpo-Xism: mobile real-estate feed and apartment interface screens.",
      "width": 1920,
      "height": 2081,
      "caption": "The mobile feed and apartment interfaces through which visitors navigate the L-B plane."
    },
    {
      "src": "/artworks/banpo-xism/7.webp",
      "alt": "Banpo-Xism: magenta geometric apartment forms projected across the media wall.",
      "width": 1920,
      "height": 1281,
      "caption": "A magenta transformation of the apartment field on the Media Wall."
    },
    {
      "src": "/artworks/banpo-xism/8.webp",
      "alt": "Banpo-Xism: the Media Wall apartment field changes from a plane to geometric forms.",
      "caption": "Screen captures trace the Media Wall from the initial 2D apartment plane to interactive higher-dimensional forms.",
      "width": 1920,
      "height": 1200
    },
    {
      "src": "/artworks/banpo-xism/9.webp",
      "alt": "Banpo-Xism: three vertical screens showing transformed apartment coordinates and text.",
      "width": 1920,
      "height": 1281,
      "caption": "The three TVs display transformed location, brand, and apartment coordinates."
    },
    {
      "src": "/artworks/banpo-xism/10.webp",
      "alt": "Banpo-Xism: composite of geometric variations generated by audience interaction.",
      "width": 1920,
      "height": 1200,
      "caption": "Variations of the apartment field produced through audience interaction."
    },
    {
      "src": "/artworks/banpo-xism/11.webp",
      "alt": "Banpo-Xism: media Wall and mobile views of the deforming apartment field.",
      "caption": "Synchronized Media Wall and mobile views show scrolling deforming the flat apartment plane.",
      "width": 1920,
      "height": 3584
    },
    {
      "src": "/artworks/banpo-xism/12.webp",
      "alt": "Banpo-Xism: wide installation view showing the three screens and changing media wall.",
      "width": 1920,
      "height": 1281,
      "caption": "The Media Wall and three vertical TVs during a geometric transformation."
    },
    {
      "src": "/artworks/banpo-xism/13.webp",
      "alt": "Banpo-Xism: the three vertical TVs before and after audience interaction.",
      "caption": "The three TVs show the L-axis, L-B plane, and B-axis before and after higher-dimensional interaction.",
      "width": 1920,
      "height": 2256
    },
    {
      "src": "/artworks/banpo-xism/14.webp",
      "alt": "Banpo-Xism: apartment names and coordinates densely layered across three displays.",
      "width": 1920,
      "height": 1120,
      "caption": "Apartment names and coordinates form dense text towers across the three TVs."
    },
    {
      "src": "/artworks/banpo-xism/15.webp",
      "alt": "Banpo-Xism: media Wall transformations and mobile links to hidden dimensions.",
      "caption": "Nine hidden-dimension links let visitors transform the apartment field and its visual presentation.",
      "width": 1920,
      "height": 1082
    },
    {
      "src": "/artworks/banpo-xism/16.webp",
      "alt": "Banpo-Xism: large white folded apartment field projected in the gallery.",
      "width": 1920,
      "height": 1281,
      "caption": "A white folded apartment field projected at installation scale."
    }
  ],
  video: { label: "Watch video ↗", url: "https://www.youtube.com/watch?v=1tA1aEc7Ato" },
  content: { en: {
  "title": "Banpo-Xism",
  "summary": "『Banpo-Xism』 (반포자이즘) addresses South Korea’s apartment culture as a contemporary myth in which location and brand operate as coordinates of wealth, status, and aspiration. The work translates this into a multi-device web artwork in which audience mobile phones are synchronized with surrounding screens. Audiences first scroll through an SNS-like feed of fictional apartment complexes arranged by location and brand. Each scroll updates the surrounding screens as a step toward higher coordinates, while remaining confined to a flat apartment plane. Later, mobile interactions collectively deform this field into higher-dimensional geometric forms, shifting coordinates, prices, and textual hierarchies across the installation. Thus, 『Banpo-Xism』 makes social myth visible as a coordinate system audiences enter, perform, and destabilize.",
  "paragraphs": [
    "Banpo-Xism (반포자이즘), a term coined by the artists, names this contemporary Korean social thread: a blind, zero-sum competition toward the same idealised real-estate coordinate of location (L) and brand (B). Within this L-B plane, people compare, compete, and pursue higher coordinates. This recalls Abbott’s satirical novella <Flatland>, in which two-dimensional beings mistake their plane for reality, unable to imagine dimensions beyond it. From a higher-dimensional view, however, Flatland’s laws appear narrow, arbitrary, and almost absurd. 『Banpo-Xism』 experiments with a similar proposition: Banpo-Xi, the apparent ultimate coordinate of success, may be only a flattened projection of a larger higher-dimensional field.",
    "Through iterative mathematical, geometric, and interaction trials, the artists designed the following system: 『Banpo-Xism』 begins on a two-dimensional L-B plane containing 19 x 19 apartment complexes. Lower-value complexes occupy the bottom-left, while Banpo-Xi sits at the upper-right, with prices ranked according to each apartment’s L/B position. Audience members enter a custom mobile web app, beginning with an Instagram-like vertical feed: a synthetic real-estate social-media world of fictional apartment posts and status-anxious comments such as, “Honestly, people’s faces change when I say I live in Banpo-Xi.” As they doom-scroll, their (L, B) coordinate moves upward. The same movement is updated in real time on surrounding screens, where multiple audience members appear at once, blindly competing to reach the upper-right.",
    "Yet the moment they click an advertisement, “Enter a higher-dimensional world,” they slip out of the two-dimensional plane. Each link reveals a hidden variable beyond L/B, opening an adjustable dimension. As these dimensions are adjusted, the flat apartment plane begins to fold, spin, scatter, and come alive as a differentiable manifold. By touching, shaking, and shouting into their phones, audience members turn hidden constants into interactive parameters, adding dimensions and deforming the field of apartments.",
    "Drawing on differential geometry, 『Banpo-Xism』 gives mathematical form to a world beyond the flatness of the L-B plane. As the manifold is projected back onto the L-B coordinate, apartment prices fluctuate, revealing Banpo-Xism’s hierarchy as a lower-dimensional projection of a higher-dimensional value system."
  ],
  "medium": "Multi-Device Web Artwork (1 Media Wall, 3 TVs, Multiple Audiences' Mobiles)"
} },
  references: [
  {
    "label": "XD Lab",
    "url": "https://www.xdlab.net/projects/banpo-xism"
  },
  {
    "label": "Interactive artwork",
    "url": "https://banpo-xism.vercel.app/"
  }
],
};
